// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadConanchor returns the embedded CollectionSpec for conanchor.
func loadConanchor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConanchorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load conanchor: %w", err)
	}

	return spec, err
}

// loadConanchorObjects loads conanchor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*conanchorObjects
//	*conanchorPrograms
//	*conanchorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConanchorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConanchor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// conanchorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conanchorSpecs struct {
	conanchorProgramSpecs
	conanchorMapSpecs
	conanchorVariableSpecs
}

// conanchorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conanchorProgramSpecs struct {
	HandleBprmCheckSecurity *ebpf.ProgramSpec `ebpf:"handle_bprm_check_security"`
	HandleFileOpen          *ebpf.ProgramSpec `ebpf:"handle_file_open"`
	HandleSbMount           *ebpf.ProgramSpec `ebpf:"handle_sb_mount"`
}

// conanchorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conanchorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// conanchorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conanchorVariableSpecs struct {
}

// conanchorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConanchorObjects or ebpf.CollectionSpec.LoadAndAssign.
type conanchorObjects struct {
	conanchorPrograms
	conanchorMaps
	conanchorVariables
}

func (o *conanchorObjects) Close() error {
	return _ConanchorClose(
		&o.conanchorPrograms,
		&o.conanchorMaps,
	)
}

// conanchorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConanchorObjects or ebpf.CollectionSpec.LoadAndAssign.
type conanchorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *conanchorMaps) Close() error {
	return _ConanchorClose(
		m.Events,
	)
}

// conanchorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConanchorObjects or ebpf.CollectionSpec.LoadAndAssign.
type conanchorVariables struct {
}

// conanchorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConanchorObjects or ebpf.CollectionSpec.LoadAndAssign.
type conanchorPrograms struct {
	HandleBprmCheckSecurity *ebpf.Program `ebpf:"handle_bprm_check_security"`
	HandleFileOpen          *ebpf.Program `ebpf:"handle_file_open"`
	HandleSbMount           *ebpf.Program `ebpf:"handle_sb_mount"`
}

func (p *conanchorPrograms) Close() error {
	return _ConanchorClose(
		p.HandleBprmCheckSecurity,
		p.HandleFileOpen,
		p.HandleSbMount,
	)
}

func _ConanchorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed conanchor_bpfeb.o
var _ConanchorBytes []byte
